name: Go Package Filter
description: GitHub action to generate path filters based on Go dependancies
author: pecigonzalo

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: heart
  color: red

# Define your inputs here.
inputs:
  path:
    description: Go project path
    required: true
    default: "./..."

# Define your outputs here.
outputs:
  time:
    description: Your output description here

runs:
  using: node20
  main: dist/index.js
